# Generated by Django 3.0.5 on 2021-04-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postname', models.CharField(max_length=220)),
                ('post_for', models.CharField(max_length=220)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('lastdate', models.DateTimeField(verbose_name='last date')),
            ],
        ),
    ]
