# Generated by Django 3.0.5 on 2021-08-06 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=200)),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2021, 8, 6, 20, 7, 55, 299235))),
            ],
        ),
    ]
