# Generated by Django 3.0.5 on 2021-08-06 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 6, 20, 9, 3, 176317)),
        ),
    ]
