# Generated by Django 3.0.5 on 2021-08-07 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20210806_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 11, 33, 9, 182271)),
        ),
    ]
