# Generated by Django 3.0.5 on 2021-08-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=200)),
            ],
        ),
    ]
